# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_Struttura_ui.ui'
#
# Created: Mon Jul 08 19:14:05 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogStruttura(object):
    def setupUi(self, DialogStruttura):
        DialogStruttura.setObjectName(_fromUtf8("DialogStruttura"))
        DialogStruttura.resize(667, 766)
        DialogStruttura.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconStrutt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogStruttura.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(DialogStruttura)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 283))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_29 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_first_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_42 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_43 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(self.layoutWidget)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_8 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout.addWidget(self.line_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.comboBox_sito = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.gridLayout_18.addWidget(self.comboBox_sito, 0, 0, 1, 1)
        self.numero_struttura = QtGui.QLineEdit(self.layoutWidget)
        self.numero_struttura.setEnabled(False)
        self.numero_struttura.setMinimumSize(QtCore.QSize(61, 21))
        self.numero_struttura.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.numero_struttura.setFont(font)
        self.numero_struttura.setObjectName(_fromUtf8("numero_struttura"))
        self.gridLayout_18.addWidget(self.numero_struttura, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_18.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_18.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_18.addWidget(self.label_3, 1, 2, 1, 1)
        self.comboBox_sigla_struttura = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_sigla_struttura.setEnabled(False)
        self.comboBox_sigla_struttura.setMinimumSize(QtCore.QSize(90, 0))
        self.comboBox_sigla_struttura.setMaximumSize(QtCore.QSize(90, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sigla_struttura.setFont(font)
        self.comboBox_sigla_struttura.setEditable(True)
        self.comboBox_sigla_struttura.setObjectName(_fromUtf8("comboBox_sigla_struttura"))
        self.comboBox_sigla_struttura.addItem(_fromUtf8(""))
        self.comboBox_sigla_struttura.addItem(_fromUtf8(""))
        self.gridLayout_18.addWidget(self.comboBox_sigla_struttura, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_18)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.comboBox_categoria_struttura = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_categoria_struttura.setFont(font)
        self.comboBox_categoria_struttura.setEditable(True)
        self.comboBox_categoria_struttura.setObjectName(_fromUtf8("comboBox_categoria_struttura"))
        self.gridLayout_6.addWidget(self.comboBox_categoria_struttura, 0, 0, 1, 1)
        self.comboBox_tipologia_struttura = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_tipologia_struttura.setFont(font)
        self.comboBox_tipologia_struttura.setEditable(True)
        self.comboBox_tipologia_struttura.setObjectName(_fromUtf8("comboBox_tipologia_struttura"))
        self.gridLayout_6.addWidget(self.comboBox_tipologia_struttura, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 1, 1, 1)
        self.comboBox_definizione_struttura = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_definizione_struttura.setFont(font)
        self.comboBox_definizione_struttura.setEditable(True)
        self.comboBox_definizione_struttura.setObjectName(_fromUtf8("comboBox_definizione_struttura"))
        self.gridLayout_6.addWidget(self.comboBox_definizione_struttura, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget = QtGui.QTabWidget(DialogStruttura)
        self.tabWidget.setGeometry(QtCore.QRect(13, 276, 532, 453))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.textEdit_descrizione_struttura = QtGui.QTextEdit(self.tab)
        self.textEdit_descrizione_struttura.setMinimumSize(QtCore.QSize(500, 150))
        self.textEdit_descrizione_struttura.setMaximumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_struttura.setFont(font)
        self.textEdit_descrizione_struttura.setObjectName(_fromUtf8("textEdit_descrizione_struttura"))
        self.verticalLayout_5.addWidget(self.textEdit_descrizione_struttura)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEdit_interpretazione_struttura = QtGui.QTextEdit(self.tab)
        self.textEdit_interpretazione_struttura.setMinimumSize(QtCore.QSize(0, 150))
        self.textEdit_interpretazione_struttura.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione_struttura.setFont(font)
        self.textEdit_interpretazione_struttura.setObjectName(_fromUtf8("textEdit_interpretazione_struttura"))
        self.verticalLayout_5.addWidget(self.textEdit_interpretazione_struttura)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_15.addWidget(self.label_12, 0, 0, 1, 4)
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setMinimumSize(QtCore.QSize(0, 15))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_15.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 15))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_15.addWidget(self.label_14, 1, 3, 1, 1)
        self.comboBox_per_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_iniz.setObjectName(_fromUtf8("comboBox_per_iniz"))
        self.comboBox_per_iniz.addItem(_fromUtf8(""))
        self.comboBox_per_iniz.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox_per_iniz, 3, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_15.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_15.addWidget(self.label_16, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_15.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_15.addWidget(self.label_32, 4, 4, 1, 1)
        self.comboBox_fas_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_iniz.setObjectName(_fromUtf8("comboBox_fas_iniz"))
        self.gridLayout_15.addWidget(self.comboBox_fas_iniz, 3, 1, 1, 1)
        self.comboBox_per_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_fin.setObjectName(_fromUtf8("comboBox_per_fin"))
        self.gridLayout_15.addWidget(self.comboBox_per_fin, 3, 3, 1, 1)
        self.comboBox_fas_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_fin.setObjectName(_fromUtf8("comboBox_fas_fin"))
        self.gridLayout_15.addWidget(self.comboBox_fas_fin, 3, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_15)
        self.lineEdit_datazione_estesa = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_datazione_estesa.setObjectName(_fromUtf8("lineEdit_datazione_estesa"))
        self.verticalLayout_8.addWidget(self.lineEdit_datazione_estesa)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_8.addWidget(self.label_17)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.verticalLayout_9.addLayout(self.gridLayout_16)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_10.addWidget(self.line_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_4.addWidget(self.label_19)
        self.pushButton_insert_row_rapporti = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_rapporti.setFont(font)
        self.pushButton_insert_row_rapporti.setObjectName(_fromUtf8("pushButton_insert_row_rapporti"))
        self.horizontalLayout_4.addWidget(self.pushButton_insert_row_rapporti)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout_11)
        self.tableWidget_rapporti = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_rapporti.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_rapporti.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_rapporti.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_rapporti.setRowCount(1)
        self.tableWidget_rapporti.setColumnCount(4)
        self.tableWidget_rapporti.setObjectName(_fromUtf8("tableWidget_rapporti"))
        self.tableWidget_rapporti.setColumnCount(4)
        self.tableWidget_rapporti.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(3, item)
        self.verticalLayout_14.addWidget(self.tableWidget_rapporti)
        self.gridLayout_17.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.pushButton_insert_row_elementi = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_elementi.setGeometry(QtCore.QRect(150, 150, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_elementi.setFont(font)
        self.pushButton_insert_row_elementi.setObjectName(_fromUtf8("pushButton_insert_row_elementi"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(27, 157, 121, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tableWidget_elementi_strutturali = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_elementi_strutturali.setGeometry(QtCore.QRect(27, 182, 581, 80))
        self.tableWidget_elementi_strutturali.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_elementi_strutturali.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_elementi_strutturali.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_elementi_strutturali.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_elementi_strutturali.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_elementi_strutturali.setRowCount(1)
        self.tableWidget_elementi_strutturali.setColumnCount(2)
        self.tableWidget_elementi_strutturali.setObjectName(_fromUtf8("tableWidget_elementi_strutturali"))
        self.tableWidget_elementi_strutturali.setColumnCount(2)
        self.tableWidget_elementi_strutturali.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_strutturali.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_strutturali.setHorizontalHeaderItem(1, item)
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(27, 303, 76, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tableWidget_misurazioni = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_misurazioni.setGeometry(QtCore.QRect(27, 328, 581, 80))
        self.tableWidget_misurazioni.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_misurazioni.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_misurazioni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_misurazioni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_misurazioni.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_misurazioni.setRowCount(1)
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setObjectName(_fromUtf8("tableWidget_misurazioni"))
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(2, item)
        self.pushButton_insert_row_misurazioni = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_misurazioni.setGeometry(QtCore.QRect(100, 300, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_misurazioni.setFont(font)
        self.pushButton_insert_row_misurazioni.setObjectName(_fromUtf8("pushButton_insert_row_misurazioni"))
        self.tableWidget_materiali_impiegati = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_materiali_impiegati.setGeometry(QtCore.QRect(30, 30, 581, 101))
        self.tableWidget_materiali_impiegati.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_materiali_impiegati.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_materiali_impiegati.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_materiali_impiegati.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_materiali_impiegati.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_materiali_impiegati.setRowCount(1)
        self.tableWidget_materiali_impiegati.setColumnCount(1)
        self.tableWidget_materiali_impiegati.setObjectName(_fromUtf8("tableWidget_materiali_impiegati"))
        self.tableWidget_materiali_impiegati.setColumnCount(1)
        self.tableWidget_materiali_impiegati.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_materiali_impiegati.setHorizontalHeaderItem(0, item)
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 117, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pushButton_insert_row_materiali = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_materiali.setGeometry(QtCore.QRect(150, 0, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_materiali.setFont(font)
        self.pushButton_insert_row_materiali.setObjectName(_fromUtf8("pushButton_insert_row_materiali"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_4)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.pushButton_pdf_exp = QtGui.QPushButton(self.tab_4)
        self.pushButton_pdf_exp.setObjectName(_fromUtf8("pushButton_pdf_exp"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButton_pdf_exp)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(DialogStruttura)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogStruttura)

    def retranslateUi(self, DialogStruttura):
        DialogStruttura.setWindowTitle(QtGui.QApplication.translate("DialogStruttura", "pyArchInit Gestione Scavi - Scheda Struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogStruttura", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("DialogStruttura", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("DialogStruttura", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("DialogStruttura", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("DialogStruttura", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DialogStruttura", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DialogStruttura", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogStruttura", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DialogStruttura", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("DialogStruttura", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogStruttura", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogStruttura", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogStruttura", "Sito ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogStruttura", "Sigla struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogStruttura", "N°", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigla_struttura.setItemText(0, QtGui.QApplication.translate("DialogStruttura", "Aggiungi un valore...", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigla_struttura.setItemText(1, QtGui.QApplication.translate("DialogStruttura", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogStruttura", "Categoria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogStruttura", "Tipologia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogStruttura", "Definizione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogStruttura", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_struttura.setHtml(QtGui.QApplication.translate("DialogStruttura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:13pt;\"><br /></span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogStruttura", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogStruttura", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogStruttura", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogStruttura", "Periodizzazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("DialogStruttura", "Iniziale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogStruttura", "Finale ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz.setItemText(0, QtGui.QApplication.translate("DialogStruttura", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz.setItemText(1, QtGui.QApplication.translate("DialogStruttura", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DialogStruttura", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogStruttura", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogStruttura", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("DialogStruttura", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogStruttura", "Datazione estesa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogStruttura", "Rapporti struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_rapporti.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Tipo di rapporto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogStruttura", "Sito", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogStruttura", "Sigla", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogStruttura", "Numero", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogStruttura", "Periodizzazione - Rapporti", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_elementi.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogStruttura", "Elementi strutturali", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_strutturali.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Tipologia elemnto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_strutturali.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogStruttura", "Quantità", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogStruttura", "Misurazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Tipo misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogStruttura", "Unita\' di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogStruttura", "Valore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_misurazioni.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_materiali_impiegati.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Materiali", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogStruttura", "Materiali impiegati", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_materiali.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("DialogStruttura", "Elementi costruttivi", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setText(QtGui.QApplication.translate("DialogStruttura", "PDF exp", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("DialogStruttura", "Tools", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
