# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\.qgis2\python\plugins\pyarchinit\modules\gui\Ui_pyarchinitConfig.ui'
#
# Created: Mon Apr 07 16:43:54 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Config(object):
    def setupUi(self, Dialog_Config):
        Dialog_Config.setObjectName(_fromUtf8("Dialog_Config"))
        Dialog_Config.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_Config.setEnabled(True)
        Dialog_Config.resize(450, 345)
        Dialog_Config.setMinimumSize(QtCore.QSize(450, 279))
        Dialog_Config.setMaximumSize(QtCore.QSize(1000, 1000))
        Dialog_Config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Dialog_Config.setMouseTracking(False)
        Dialog_Config.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconConn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Config.setWindowIcon(icon)
        Dialog_Config.setAutoFillBackground(True)
        Dialog_Config.setSizeGripEnabled(False)
        Dialog_Config.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog_Config)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Dialog_Config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setProperty("resize", _fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_Database = QtGui.QComboBox(self.tab)
        self.comboBox_Database.setEnabled(True)
        self.comboBox_Database.setMouseTracking(False)
        self.comboBox_Database.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox_Database.setAcceptDrops(False)
        self.comboBox_Database.setEditable(True)
        self.comboBox_Database.setDuplicatesEnabled(False)
        self.comboBox_Database.setFrame(True)
        self.comboBox_Database.setObjectName(_fromUtf8("comboBox_Database"))
        self.comboBox_Database.addItem(_fromUtf8(""))
        self.comboBox_Database.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Database, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_Host = QtGui.QLineEdit(self.tab)
        self.lineEdit_Host.setObjectName(_fromUtf8("lineEdit_Host"))
        self.gridLayout.addWidget(self.lineEdit_Host, 1, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_Port = QtGui.QLineEdit(self.tab)
        self.lineEdit_Port.setObjectName(_fromUtf8("lineEdit_Port"))
        self.gridLayout.addWidget(self.lineEdit_Port, 2, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_DBname = QtGui.QLineEdit(self.tab)
        self.lineEdit_DBname.setObjectName(_fromUtf8("lineEdit_DBname"))
        self.gridLayout.addWidget(self.lineEdit_DBname, 3, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_User = QtGui.QLineEdit(self.tab)
        self.lineEdit_User.setObjectName(_fromUtf8("lineEdit_User"))
        self.gridLayout.addWidget(self.lineEdit_User, 4, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_Password = QtGui.QLineEdit(self.tab)
        self.lineEdit_Password.setInputMask(_fromUtf8(""))
        self.lineEdit_Password.setText(_fromUtf8("\'\'"))
        self.lineEdit_Password.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_Password.setObjectName(_fromUtf8("lineEdit_Password"))
        self.gridLayout.addWidget(self.lineEdit_Password, 5, 1, 1, 2)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 2)
        self.lineEdit_Thumb_path = QtGui.QLineEdit(self.tab)
        self.lineEdit_Thumb_path.setObjectName(_fromUtf8("lineEdit_Thumb_path"))
        self.gridLayout.addWidget(self.lineEdit_Thumb_path, 6, 2, 1, 1)
        self.pushButton_save = QtGui.QPushButton(self.tab)
        self.pushButton_save.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_save.setCheckable(False)
        self.pushButton_save.setAutoDefault(True)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 7, 1, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pushButton_crea_layer_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_crea_layer_2.setEnabled(True)
        self.pushButton_crea_layer_2.setGeometry(QtCore.QRect(330, 240, 75, 23))
        self.pushButton_crea_layer_2.setObjectName(_fromUtf8("pushButton_crea_layer_2"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 271, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_dbname = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_dbname.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.lineEdit_dbname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_dbname.setDragEnabled(False)
        self.lineEdit_dbname.setReadOnly(False)
        self.lineEdit_dbname.setObjectName(_fromUtf8("lineEdit_dbname"))
        self.lineEdit_template_postgis = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_template_postgis.setGeometry(QtCore.QRect(10, 60, 113, 20))
        self.lineEdit_template_postgis.setObjectName(_fromUtf8("lineEdit_template_postgis"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(130, 30, 131, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(130, 60, 131, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(150, 192, 141, 41))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_port_db = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_port_db.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_port_db.setObjectName(_fromUtf8("lineEdit_port_db"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(130, 90, 121, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pyarchinit_progressBar_db = QtGui.QProgressBar(self.tab_2)
        self.pyarchinit_progressBar_db.setGeometry(QtCore.QRect(10, 120, 121, 23))
        self.pyarchinit_progressBar_db.setProperty("value", 1)
        self.pyarchinit_progressBar_db.setAlignment(QtCore.Qt.AlignCenter)
        self.pyarchinit_progressBar_db.setOrientation(QtCore.Qt.Horizontal)
        self.pyarchinit_progressBar_db.setInvertedAppearance(False)
        self.pyarchinit_progressBar_db.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.pyarchinit_progressBar_db.setObjectName(_fromUtf8("pyarchinit_progressBar_db"))
        self.pyarchinit_progressBar_template = QtGui.QProgressBar(self.tab_2)
        self.pyarchinit_progressBar_template.setGeometry(QtCore.QRect(10, 200, 118, 23))
        self.pyarchinit_progressBar_template.setProperty("value", 1)
        self.pyarchinit_progressBar_template.setAlignment(QtCore.Qt.AlignCenter)
        self.pyarchinit_progressBar_template.setOrientation(QtCore.Qt.Horizontal)
        self.pyarchinit_progressBar_template.setInvertedAppearance(False)
        self.pyarchinit_progressBar_template.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.pyarchinit_progressBar_template.setObjectName(_fromUtf8("pyarchinit_progressBar_template"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 90, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_crea_layer = QtGui.QPushButton(self.tab_2)
        self.pushButton_crea_layer.setEnabled(True)
        self.pushButton_crea_layer.setGeometry(QtCore.QRect(330, 140, 75, 23))
        self.pushButton_crea_layer.setObjectName(_fromUtf8("pushButton_crea_layer"))
        self.pushButton_crea_database = QtGui.QPushButton(self.tab_2)
        self.pushButton_crea_database.setEnabled(True)
        self.pushButton_crea_database.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.pushButton_crea_database.setObjectName(_fromUtf8("pushButton_crea_database"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 291, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_exp_directories = QtGui.QPushButton(self.tab_3)
        self.pushButton_exp_directories.setObjectName(_fromUtf8("pushButton_exp_directories"))
        self.gridLayout_4.addWidget(self.pushButton_exp_directories, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog_Config)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Config)
        Dialog_Config.setTabOrder(self.comboBox_Database, self.lineEdit_Host)
        Dialog_Config.setTabOrder(self.lineEdit_Host, self.lineEdit_Port)
        Dialog_Config.setTabOrder(self.lineEdit_Port, self.lineEdit_DBname)
        Dialog_Config.setTabOrder(self.lineEdit_DBname, self.lineEdit_User)
        Dialog_Config.setTabOrder(self.lineEdit_User, self.lineEdit_Password)

    def retranslateUi(self, Dialog_Config):
        Dialog_Config.setWindowTitle(_translate("Dialog_Config", "Impostazioni del sistema", None))
        self.label.setText(_translate("Dialog_Config", "Database", None))
        self.comboBox_Database.setItemText(0, _translate("Dialog_Config", "postgres", None))
        self.comboBox_Database.setItemText(1, _translate("Dialog_Config", "sqlite", None))
        self.label_2.setText(_translate("Dialog_Config", "Host", None))
        self.lineEdit_Host.setText(_translate("Dialog_Config", "\'\'", None))
        self.label_7.setText(_translate("Dialog_Config", "Port", None))
        self.lineEdit_Port.setText(_translate("Dialog_Config", "\'\'", None))
        self.label_3.setText(_translate("Dialog_Config", "DBname", None))
        self.lineEdit_DBname.setText(_translate("Dialog_Config", "\'\'", None))
        self.label_4.setText(_translate("Dialog_Config", "User", None))
        self.lineEdit_User.setText(_translate("Dialog_Config", "\'\'", None))
        self.label_5.setText(_translate("Dialog_Config", "Password", None))
        self.label_10.setText(_translate("Dialog_Config", "Thumbnail path", None))
        self.lineEdit_Thumb_path.setText(_translate("Dialog_Config", "\'\'", None))
        self.pushButton_save.setText(_translate("Dialog_Config", "Connect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog_Config", "Parametri di connessione", None))
        self.pushButton_crea_layer_2.setText(_translate("Dialog_Config", "Installa", None))
        self.label_9.setText(_translate("Dialog_Config", "Installa il db geografico su Postgres per postgis 2.x", None))
        self.lineEdit_dbname.setText(_translate("Dialog_Config", "pyarchinit", None))
        self.lineEdit_template_postgis.setText(_translate("Dialog_Config", "template_postgis_20", None))
        self.label_12.setToolTip(_translate("Dialog_Config", "<html><head/><body><p><span style=\" font-size:10pt;\">Puoi inserire un nome differente da quello presente</span></p></body></html>", None))
        self.label_12.setText(_translate("Dialog_Config", "inserisci nome db", None))
        self.label_13.setToolTip(_translate("Dialog_Config", "<html><head/><body><p>qui devi inserire il nome del template che vuoi usare. Ricorda di usare il template specifico a seconda di quale postgis usi</p></body></html>", None))
        self.label_13.setText(_translate("Dialog_Config", "inserisci nome template", None))
        self.label_14.setText(_translate("Dialog_Config", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">OPPURE</span></p></body></html>", None))
        self.lineEdit_port_db.setText(_translate("Dialog_Config", "5432", None))
        self.label_15.setToolTip(_translate("Dialog_Config", "<html><head/><body><p><span style=\" font-size:10pt;\">puoi inserire il numero di porta differente</span></p></body></html>", None))
        self.label_15.setText(_translate("Dialog_Config", "inserisci numero porta", None))
        self.label_6.setText(_translate("Dialog_Config", "Installa il database", None))
        self.pushButton_crea_layer.setText(_translate("Dialog_Config", "Installa", None))
        self.pushButton_crea_database.setText(_translate("Dialog_Config", "Installa", None))
        self.label_8.setText(_translate("Dialog_Config", "Installa il db geografico su Postgres per postgis 1.5", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog_Config", "Installazione layers", None))
        self.pushButton_exp_directories.setText(_translate("Dialog_Config", "Esportazione", None))
        self.label_11.setText(_translate("Dialog_Config", "Esportazione directories", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog_Config", "Tool di amministrazione", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog_Config = QtGui.QDialog()
    ui = Ui_Dialog_Config()
    ui.setupUi(Dialog_Config)
    Dialog_Config.show()
    sys.exit(app.exec_())

